version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: kk_vendedores_dev
    working_dir: /app
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "corepack enable pnpm && pnpm install && pnpm dev"
    stdin_open: true
    tty: true