version: '3.8'

services:
  vendedores:
    build:
      context: ..
      dockerfile: ./PROD/Dockerfile
    container_name: vendedores
    restart: unless-stopped
    networks:
      - internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.vendedores.rule=Host(`vendedores.fullengineer.com.br`)"
      - "traefik.http.routers.vendedores.entrypoints=websecure"
      - "traefik.http.routers.vendedores.tls.certresolver=letsencrypt"
      - "traefik.http.services.vendedores.loadbalancer.server.port=80"

networks:
  internal:
    external: true
    name: internal
  proxy:
    external: true
    name: proxy