<script setup>
import { ref } from 'vue'

const groupLink = 'https://chat.whatsapp.com/JmIgDQS3xWjKZq0FSEa5rD'
const openFaq = ref(0)

const benefits = [
  ['fa-solid fa-coins', 'R$ 100 por venda', 'Comissão definida para cada venda validada por meio da sua atuação. recebimento em até 24hs, independente da quantidade de vendas.'],
  ['fa-solid fa-gift', 'Bônus a cada 5 vendas', 'Parabenizamos seus esforços com bonificações adicionais a cada 5 vendas. R$ 200 a mais como bônus.'],
  ['fa-solid fa-graduation-cap', 'Treinamento completo', 'Produto, funil e técnicas de argumentação para vender com clareza. Como usar IA´s gratuitas, as ferramentas e links de venda e de desconto.'],
  ['fa-solid fa-toolbox', 'Estrutura para vender', 'Materiais, ferramentas e recursos para organizar sua rotina comercial.'],
  ['fa-solid fa-chart-line', 'Acompanhe seu desempenho', 'Consulte suas vendas e tenha mais clareza sobre a sua evolução.'],
  ['fa-solid fa-rocket', 'Conhecimento aplicável', 'Técnicas que podem ser adaptadas a outros produtos e mercados.']
]
const modules = [
  ['01', 'Conheça o produto', 'Entenda a proposta da mentoria, seus benefícios, público e diferenciais.'],
  ['02', 'Entenda o funil', 'Conduza uma pessoa desde o primeiro contato até a tomada de decisão.'],
  ['03', 'Melhore sua argumentação', 'Responda dúvidas e comunique valor sem pressionar ou prometer demais.'],
  ['04', 'Faça o acompanhamento', 'Organize conversas e faça follow-up de maneira profissional.']
]
const faqs = [
  ['Quanto recebo por venda?', 'A comissão informada é de R$ 100 por venda validada, conforme as regras do programa.'],
  ['Existe algum bônus?', 'Sim. Há previsão de bônus adicional a cada 5 vendas, de acordo com os critérios e condições apresentados no grupo.'],
  ['Preciso ter experiência com vendas?', 'Não necessariamente. O programa oferece treinamento sobre o produto, funil de vendas e argumentação.'],
  ['Vou receber treinamento?', 'Sim. Você terá acesso a vídeos explicativos e materiais práticos relacionados ao produto, ao funil e à comunicação comercial.'],
  ['Terei acesso a ferramentas?', 'Sim. Os vendedores terão acesso às ferramentas disponibilizadas pelo programa e a um painel para acompanhar resultados.'],
  ['Posso usar as técnicas em outros produtos?', 'Sim. Os conceitos de abordagem, funil e argumentação podem ser adaptados para diferentes produtos, serviços e mercados.'],
  ['Como faço para participar?', 'Clique em qualquer botão de inscrição e entre no grupo de dúvidas e seleção. As próximas orientações serão apresentadas por lá.'],
  ['Existe garantia de ganhos?', 'Não. Os resultados dependem de fatores como dedicação, abordagem, volume de contatos e vendas validadas.']
]
const ideal = ['Gosta de conversar e criar conexões.', 'Tem facilidade com redes sociais e aplicativos de comunicação.', 'Está disposto a aprender novas técnicas.', 'É organizado e acompanha os próprios resultados.', 'Quer desenvolver comunicação e argumentação.', 'Busca uma oportunidade baseada em desempenho.']
const notNeed = ['Ter experiência profissional em vendas.', 'Possuir uma grande audiência nas redes sociais.', 'Saber utilizar ferramentas complexas.', 'Prometer resultados aos clientes.', 'Abordar pessoas de maneira invasiva.']
</script>

<template>
  <div>
    <header class="sticky top-0 z-50 border-b border-white/10 bg-[#10233F]/95 text-white backdrop-blur">
      <div class="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 lg:px-8">
        <a href="#top" class="flex items-center gap-2" aria-label="Revenda Mentoria Full Engineer, voltar ao início">
          <span class="flex h-8 w-8 items-center justify-center rounded-xl bg-[#F4C95D] text-[#10233F]"><i class="fa-solid fa-arrow-trend-up" aria-hidden="true"></i></span>
          <span class="text-sm font-extrabold tracking-tight hidden sm:inline lg:text-base">Revenda <span class="text-[#F4C95D]">Mentoria Full Engineer</span></span>
        </a>
        <nav class="hidden items-center gap-5 text-sm text-blue-100 lg:flex" aria-label="Navegação principal">
          <a href="#como-funciona" class="transition hover:text-[#F4C95D]">Como funciona</a>
          <a href="#beneficios" class="transition hover:text-[#F4C95D]">Benefícios</a>
          <a href="#duvidas" class="transition hover:text-[#F4C95D]">Dúvidas</a>
        </nav>
        <a :href="groupLink" target="_blank" rel="noopener" class="rounded-full bg-[#F4C95D] px-4 py-2 text-sm font-extrabold text-[#10233F] shadow-lg shadow-yellow-500/10 transition hover:-translate-y-0.5 hover:bg-white">Quero participar <i class="fa-solid fa-arrow-right ml-1" aria-hidden="true"></i></a>
      </div>
    </header>

    <main id="top">
      <section class="relative overflow-hidden bg-premium-gradient text-white">
        <div class="grid-paper absolute inset-0 opacity-50"></div>
        <div class="absolute right-0 top-10 h-64 w-64 rounded-full bg-[#F4C95D]/20 blur-3xl lg:-right-32 lg:h-96 lg:w-96"></div>
        <div class="absolute left-0 bottom-0 h-48 w-48 rounded-full bg-blue-300/10 blur-3xl lg:-left-32 lg:h-80 lg:w-80"></div>
        <div class="relative mx-auto grid max-w-7xl items-center gap-12 px-4 py-12 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24">
          <div class="reveal">
            <div class="mb-5 inline-flex items-center gap-2 rounded-full border border-[#F4C95D]/40 bg-white/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.14em] text-[#F4C95D]"><span>🚀</span> Programa de vendedores da mentoria</div>
            <h1 class="max-w-3xl text-3xl font-black leading-[1.05] tracking-tight sm:text-4xl lg:text-5xl xl:text-6xl">Faça Dinheiro com sua rede de contatos. <span class="text-[#F4C95D]">R$ 100 por venda efetivada.</span></h1>
            <p class="mt-5 max-w-2xl text-sm leading-7 text-blue-100 sm:text-base">Monetize seu tempo livre. Tenha acesso a ferramentas profissionais, recursos e treinamentos. Oferecemos bônus de desempenho.</p>
            <div class="mt-7 flex flex-col gap-3 sm:flex-row sm:items-center"><a :href="groupLink" target="_blank" rel="noopener" class="inline-flex items-center justify-center rounded-full bg-gold-gradient px-5 py-3 text-center font-extrabold text-[#10233F] shadow-xl shadow-yellow-900/20 transition hover:-translate-y-1 hover:brightness-105">Quero entrar no processo de seleção <i class="fa-solid fa-arrow-right ml-1.5" aria-hidden="true"></i></a><span class="text-xs text-blue-200 text-center sm:text-left">Entre no grupo de dúvidas e receba as próximas orientações.</span></div>
            <div class="mt-7 flex items-center gap-4 border-t border-white/15 pt-5 text-xs text-blue-100"><span class="flex -space-x-1.5"><span class="h-7 w-7 rounded-full border-2 border-[#174EA6] bg-[#F4C95D]"></span><span class="h-7 w-7 rounded-full border-2 border-[#174EA6] bg-blue-200"></span><span class="h-7 w-7 rounded-full border-2 border-[#174EA6] bg-white"></span></span><span>Pagamento em até 24 horas. Confirmou, recebeu!</span></div>
          </div>
          <div class="relative reveal [animation-delay:150ms]">
            <div class="absolute -inset-2 rounded-[2rem] bg-[#F4C95D]/20 blur-2xl"></div>
            <div class="relative overflow-hidden rounded-[2rem] border border-white/20 bg-white/10 p-2 shadow-2xl"><img src="/images/hero-training.jpg" alt="Equipe em treinamento comercial trabalhando com laptops" class="h-[280px] w-full rounded-[1.5rem] object-cover sm:h-[340px] lg:h-[400px]" /><div class="absolute bottom-5 left-5 right-5 grid gap-2.5 sm:grid-cols-3"><div class="rounded-xl bg-white p-3 text-[#10233F] shadow-lg"><i class="fa-solid fa-coins text-lg text-[#D4A72C]" aria-hidden="true"></i><p class="mt-2 text-[10px] font-semibold text-slate-500">Comissão por venda</p><p class="text-xl font-black">R$ 100</p></div><div class="rounded-xl bg-[#10233F] p-3 text-white shadow-lg"><i class="fa-solid fa-gift text-lg text-[#F4C95D]" aria-hidden="true"></i><p class="mt-2 text-[10px] font-semibold text-blue-200">Bônus progressivo</p><p class="text-base font-black">A cada 5 vendas</p></div><div class="rounded-xl bg-white p-3 text-[#10233F] shadow-lg"><i class="fa-solid fa-chart-line text-lg text-blue-600" aria-hidden="true"></i><p class="mt-2 text-[10px] font-semibold text-slate-500">Treinamento prático</p><p class="text-base font-black">Para vender melhor</p></div></div></div>
          </div>
        </div>
      </section>

      <section id="oportunidade" class="bg-white px-4 py-16 lg:px-8 lg:py-24"><div class="mx-auto max-w-7xl"><div class="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><span class="eyebrow">01 / oportunidade</span><h2 class="section-title">Uma oportunidade para quem gosta de vender e quer evoluir</h2><p class="section-copy">Você não precisa começar sabendo tudo. Nós oferecemos uma estrutura, aplicações, informações, táticas para ajudar você a vender e acompanhar o seu desenvolvimento comercial.</p></div><div class="relative overflow-hidden rounded-2xl bg-slate-100"><img src="/images/team-training.jpg" alt="Equipe colaborando em treinamento de vendas com laptops e quadros" class="h-[350px] w-full object-cover opacity-90 lg:h-[420px]"/></div></div><div class="mt-10 lg:mt-0 lg:col-span-2"><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"> <article v-for="(item, i) in benefits" :key="item[1]" class="card group"><span class="icon-box"><i :class="item[0]" aria-hidden="true"></i></span><p class="mt-5 text-base font-extrabold">{{ item[1] }}</p><p class="mt-2 text-sm leading-6 text-slate-600">{{ item[2] }}</p><span class="mt-5 block text-xs font-bold uppercase tracking-wider text-[#174EA6]">0{{ i + 1 }} <i class="fa-solid fa-arrow-up-right-from-square ml-1 opacity-0 transition group-hover:opacity-100" aria-hidden="true"></i></span></article></div></div></div></section>

      <section id="beneficios" class="bg-[#F4F7FB] px-5 py-20 lg:px-8 lg:py-28"><div class="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><span class="eyebrow">02 / o que você recebe</span><h2 class="section-title">Você recebe mais do que um link de vendas</h2><p class="section-copy">A proposta é oferecer uma estrutura de desenvolvimento comercial. Você terá acesso a conteúdo, materiais e orientação para transformar conversas em oportunidades com responsabilidade.</p><div class="mt-8 grid gap-3 sm:grid-cols-2"><div v-for="text in ['Treinamento sobre a mentoria e seus diferenciais','Vídeos sobre o funil de vendas','Conteúdos de abordagem e argumentação','Materiais de apoio para suas conversas','Ferramentas para facilitar a rotina','Painel para acompanhar resultados','Orientações para melhorar sua comunicação','Técnicas adaptáveis a outros produtos']" :key="text" class="flex gap-3 text-sm leading-6 text-slate-700"><span class="mt-1 text-[#D4A72C]"><i class="fa-solid fa-circle-check" aria-hidden="true"></i></span>{{ text }}</div></div><p class="mt-8 border-l-4 border-[#F4C95D] pl-4 text-sm font-bold italic text-[#174EA6]">Aprenda uma habilidade que pode continuar útil mesmo depois de uma campanha ou produto.</p></div><div class="relative"><div class="absolute -inset-5 rounded-[2rem] bg-blue-900/10 blur-2xl"></div><div class="relative overflow-hidden rounded-[2rem] bg-[#10233F] p-3 shadow-premium"><img src="/images/dashboard-hands.jpg" alt="Mãos usando um laptop com visualização de dados de vendas" class="h-[400px] w-full rounded-[1.5rem] object-cover opacity-80"/><div class="absolute bottom-8 left-8 right-8 rounded-2xl border border-white/20 bg-[#10233F]/90 p-5 text-white backdrop-blur"><div class="flex items-center justify-between"><span class="text-xs font-bold uppercase tracking-[.16em] text-blue-200">Painel de evolução</span><span class="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-300">Acompanhe</span></div><div class="mt-5 flex items-end gap-2"><div v-for="n in [38,52,44,70,62,88,78]" :key="n" class="flex-1 rounded-t bg-gradient-to-t from-[#174EA6] to-[#F4C95D]" :style="{height: n + 'px'}"></div></div></div></div></div></div></section>

      <section id="treinamento" class="bg-white px-5 py-20 lg:px-8 lg:py-28"><div class="mx-auto max-w-7xl"><div class="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div class="max-w-2xl"><span class="eyebrow">03 / treinamento</span><h2 class="section-title">Venda com mais clareza, estratégia e confiança</h2><p class="section-copy">Vídeos explicativos e materiais práticos para entender como funciona o produto, conduzir conversas e fazer o acompanhamento certo.</p></div><a :href="groupLink" target="_blank" rel="noopener" class="link-cta">Quero aprender e participar <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div><div class="mt-12 grid gap-4 md:grid-cols-2"> <article v-for="module in modules" :key="module[0]" class="module-card"><span class="font-mono text-sm text-[#D4A72C]">{{ module[0] }}</span><div><h3 class="text-xl font-extrabold">{{ module[1] }}</h3><p class="mt-2 text-sm leading-6 text-slate-600">{{ module[2] }}</p></div><i class="fa-solid fa-arrow-up-right-dots ml-auto self-start text-xl text-blue-200" aria-hidden="true"></i></article></div><p class="mt-8 text-center font-bold text-[#174EA6]">Conhecimento prático para transformar conversas em oportunidades.</p></div></section>

      <section id="como-funciona" class="bg-[#10233F] px-5 py-20 text-white lg:px-8 lg:py-28"><div class="mx-auto max-w-7xl"><div class="max-w-2xl"><span class="eyebrow eyebrow-dark">04 / como funciona</span><h2 class="section-title text-white">Começar é simples</h2><p class="mt-5 text-lg leading-8 text-blue-100">Você não precisa esperar saber tudo para começar. Precisa apenas ter disposição para aprender, conversar com responsabilidade e acompanhar seu processo.</p></div><div class="mt-12 grid gap-3 md:grid-cols-5"> <div v-for="(step, i) in [['Entre no grupo','Clique no botão e entre no grupo de dúvidas e seleção.'],['Conheça o processo','Receba as orientações sobre o programa, critérios e próximas etapas.'],['Faça o treinamento','Assista aos vídeos, conheça o produto e aprenda as técnicas.'],['Comece a vender','Use os materiais e ferramentas para iniciar sua atuação.'],['Acompanhe resultados','Consulte suas vendas e avance em direção aos bônus.']]" :key="step[0]" class="relative rounded-2xl border border-white/10 bg-white/5 p-5"><span class="font-mono text-3xl font-bold text-[#F4C95D]">0{{ i + 1 }}</span><h3 class="mt-8 font-extrabold">{{ step[0] }}</h3><p class="mt-2 text-sm leading-6 text-blue-100/75">{{ step[1] }}</p><i v-if="i < 4" class="fa-solid fa-arrow-right absolute -right-3 top-8 z-10 hidden text-[#F4C95D] md:block" aria-hidden="true"></i></div></div></div></section>

      <section id="bonus" class="bg-[#F4F7FB] px-5 py-20 lg:px-8 lg:py-28"><div class="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1fr_.9fr]"><div><span class="eyebrow">05 / progresso</span><h2 class="section-title">Quanto mais você evolui, mais oportunidades pode alcançar</h2><p class="section-copy">Além da comissão de R$ 100 por venda, o programa oferece bônus adicionais a cada 5 vendas, de acordo com os critérios do programa.</p><a :href="groupLink" target="_blank" rel="noopener" class="mt-8 inline-flex items-center rounded-full bg-[#10233F] px-6 py-3.5 font-extrabold text-white transition hover:bg-[#174EA6]">Quero conhecer as condições <i class="fa-solid fa-arrow-right ml-2" aria-hidden="true"></i></a></div><div class="rounded-[2rem] bg-premium-gradient p-8 text-white shadow-premium"><div class="flex items-center justify-between border-b border-white/15 pb-5"><span class="text-sm font-bold uppercase tracking-[.18em] text-[#F4C95D]">Ciclo de crescimento</span><i class="fa-solid fa-arrows-rotate text-xl text-[#F4C95D]" aria-hidden="true"></i></div><div class="mt-8 flex items-center justify-between gap-3 text-center"><div><span class="flex h-16 w-16 items-center justify-center rounded-2xl bg-white/10 text-2xl font-black">5</span><p class="mt-3 text-xs text-blue-100">vendas</p></div><i class="fa-solid fa-arrow-right text-[#F4C95D]" aria-hidden="true"></i><div><span class="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#F4C95D] text-2xl font-black text-[#10233F]">+</span><p class="mt-3 text-xs text-blue-100">bônus adicional</p></div><i class="fa-solid fa-arrow-right text-[#F4C95D]" aria-hidden="true"></i><div><span class="flex h-16 w-16 items-center justify-center rounded-2xl bg-white/10 text-2xl font-black">↗</span><p class="mt-3 text-xs text-blue-100">novo ciclo</p></div></div><p class="mt-9 rounded-xl bg-black/10 p-4 text-sm text-blue-100">Os bônus, critérios de validação e condições de pagamento serão apresentados no grupo.</p></div></div></section>

      <section id="perfil" class="bg-white px-5 py-20 lg:px-8 lg:py-28"><div class="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><div class="rounded-[2rem] bg-[#F4F7FB] p-8 lg:p-10"><span class="eyebrow">06 / perfil ideal</span><h2 class="mt-4 text-3xl font-black tracking-tight">Essa oportunidade pode fazer sentido para você se...</h2><ul class="mt-8 space-y-4"> <li v-for="item in ideal" :key="item" class="flex gap-3 text-sm leading-6 text-slate-700"><span class="text-[#174EA6]">✓</span>{{ item }}</li></ul></div><div class="rounded-[2rem] border border-slate-200 p-8 lg:p-10"><span class="eyebrow text-slate-500">não é necessário</span><h2 class="mt-4 text-3xl font-black tracking-tight">Você não precisa...</h2><ul class="mt-8 space-y-4"> <li v-for="item in notNeed" :key="item" class="flex gap-3 text-sm leading-6 text-slate-600"><span class="text-slate-400">×</span>{{ item }}</li></ul><p class="mt-8 border-t border-slate-200 pt-6 text-sm leading-6 text-slate-600">O mais importante é ter responsabilidade, ética, disposição para aprender e respeito pelas pessoas.</p></div></div></section>

      <section class="bg-[#F4F7FB] px-5 py-20 lg:px-8"><div class="mx-auto max-w-7xl"><div class="text-center"><span class="eyebrow">07 / credibilidade</span><h2 class="section-title mx-auto max-w-2xl">Uma estrutura para você vender de forma profissional</h2><p class="section-copy mx-auto">A proposta do programa é ajudar você a desenvolver uma atuação comercial mais organizada, com conteúdo e acompanhamento.</p></div><div class="mt-12 grid gap-4 md:grid-cols-3"><div v-for="item in [['fa-solid fa-graduation-cap','Conteúdo estruturado','Aprenda em uma sequência clara e prática.'],['fa-solid fa-chart-simple','Acompanhamento de resultados','Tenha mais clareza sobre sua evolução.'],['fa-solid fa-brain','Técnicas aplicáveis','Leve os aprendizados para outras conversas e produtos.']]" :key="item[1]" class="rounded-2xl bg-white p-7 text-center shadow-sm"><i :class="item[0]" class="text-2xl text-[#D4A72C]" aria-hidden="true"></i><h3 class="mt-5 font-extrabold">{{ item[1] }}</h3><p class="mt-2 text-sm leading-6 text-slate-600">{{ item[2] }}</p></div></div></div></section>

      <section id="duvidas" class="bg-white px-5 py-20 lg:px-8 lg:py-28"><div class="mx-auto max-w-4xl"><div class="text-center"><span class="eyebrow">08 / dúvidas</span><h2 class="section-title">Perguntas frequentes</h2><p class="section-copy mx-auto">Clareza antes de entrar. Se a sua dúvida não estiver aqui, leve-a para o grupo de seleção.</p></div><div class="mt-10 divide-y divide-slate-200 rounded-3xl border border-slate-200 bg-white"> <div v-for="(faq, i) in faqs" :key="faq[0]" class="px-6"><button class="flex w-full items-center justify-between gap-5 py-5 text-left font-bold" :aria-expanded="openFaq === i" @click="openFaq = openFaq === i ? -1 : i">{{ faq[0] }}<i class="fa-solid fa-plus text-[#174EA6] transition" :class="openFaq === i ? 'rotate-45' : ''" aria-hidden="true"></i></button><p v-if="openFaq === i" class="max-w-3xl pb-5 text-sm leading-7 text-slate-600">{{ faq[1] }}</p></div></div><div class="mt-10 text-center"><a :href="groupLink" target="_blank" rel="noopener" class="inline-flex items-center rounded-full bg-gold-gradient px-7 py-4 font-extrabold text-[#10233F] shadow-lg transition hover:-translate-y-1">Quero participar do processo de seleção <i class="fa-solid fa-rocket ml-2" aria-hidden="true"></i></a></div></div></section>

      <section id="grupo-selecao" class="relative overflow-hidden bg-premium-gradient px-5 py-20 text-white lg:px-8 lg:py-28"><div class="grid-paper absolute inset-0 opacity-30"></div><div class="relative mx-auto max-w-4xl text-center"><span class="eyebrow eyebrow-dark">próximo passo</span><h2 class="mt-5 text-4xl font-black tracking-tight sm:text-5xl">Pronto para transformar sua comunicação em oportunidade?</h2><p class="mx-auto mt-6 max-w-2xl text-lg leading-8 text-blue-100">Entre no grupo de dúvidas e seleção para conhecer todos os detalhes do programa, tirar suas dúvidas e receber as próximas orientações.</p><a :href="groupLink" target="_blank" rel="noopener" class="mt-9 inline-flex w-full items-center justify-center rounded-full bg-[#F4C95D] px-7 py-4 font-extrabold text-[#10233F] shadow-xl transition hover:-translate-y-1 hover:bg-white sm:w-auto">Entrar no grupo agora <i class="fa-solid fa-arrow-right ml-2" aria-hidden="true"></i></a><p class="mt-5 text-xs text-blue-200">Vagas e condições sujeitas à disponibilidade do programa.</p></div></section>
    </main>

    <footer class="bg-[#0B192D] px-5 py-12 text-blue-200 lg:px-8"><div class="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row"><div><div class="flex items-center gap-3 text-white"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-[#F4C95D] text-[#10233F]"><i class="fa-solid fa-arrow-trend-up" aria-hidden="true"></i></span><span class="text-lg font-extrabold">Revenda <span class="text-[#F4C95D]">Mentoria Full Engineer</span></span></div><p class="mt-4 max-w-sm text-sm leading-6">Programa de vendedores da mentoria para quem quer desenvolver habilidades e vender com profissionalismo.</p></div><div class="grid grid-cols-2 gap-x-12 gap-y-3 text-sm"><a href="#como-funciona" class="hover:text-[#F4C95D]">Como funciona</a><a href="#beneficios" class="hover:text-[#F4C95D]">Benefícios</a><a href="#duvidas" class="hover:text-[#F4C95D]">Perguntas frequentes</a><a :href="groupLink" target="_blank" rel="noopener" class="hover:text-[#F4C95D]">Entrar no grupo</a></div></div><div class="mx-auto mt-10 max-w-7xl border-t border-white/10 pt-6 text-xs leading-6 text-blue-300/70"><p>A participação no programa não garante ganhos fixos ou resultados específicos. As comissões dependem de vendas validadas e das condições apresentadas no grupo.</p><p class="mt-2">© 2026 — Todos os direitos reservados.</p></div></footer>
  </div>
</template>

<style scoped>
.eyebrow { @apply font-mono text-[11px] font-bold uppercase tracking-[.2em] text-[#174EA6]; }
.eyebrow-dark { @apply text-[#F4C95D]; }
.section-title { @apply mt-4 text-3xl font-black tracking-tight sm:text-4xl lg:text-5xl; }
.section-copy { @apply mt-5 text-base leading-8 text-slate-600; }
.card { @apply rounded-2xl border border-slate-200 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-premium; }
.icon-box { @apply flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-xl text-[#174EA6] transition group-hover:bg-[#174EA6] group-hover:text-white; }
.module-card { @apply flex gap-5 rounded-2xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-[#F4C95D] hover:shadow-lg; }
.link-cta { @apply inline-flex items-center gap-2 font-bold text-[#174EA6] transition hover:gap-3; }
</style>
